# Generated by Django 3.0.6 on 2020-08-11 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
                ('start_date', models.DateField(blank=True, default=1, null=True)),
                ('end_date', models.DateField(blank=True, default=1, null=True)),
                ('status', models.CharField(choices=[('S', 'in-progress'), ('P', 'paused'), ('F', 'finished'), ('D', 'delivered')], default='S', max_length=1)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tecnologies', models.ManyToManyField(to='projects.Technologie')),
            ],
        ),
    ]
