# Generated by Django 3.0.6 on 2020-08-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200811_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('S', 'in-progress'), ('P', 'paused'), ('F', 'finished')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='project',
            name='tecnologies',
            field=models.ManyToManyField(to='projects.Technologie'),
        ),
    ]
