version: '3'


services:
    app:
      build: .
      container_name: iniciando-django-app
      command: python manage.py runserver 0.0.0.0:8002
      volumes:
        - .:/home/django/app
      ports:
        - "8002:8002"
      depends_on:
        - db

    mysqlsrv:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: "MySql2019!"
        MYSQL_DATABASE: "testedb"
      ports:
        - "3307:3306"
      volumes:
        - eco:/var/lib/mysql

    db:
      image: postgres
      container_name: iniciando-django-db
      tty:  true
      environment:
        - POSTGRES_DB=iniciando_django
        - POSRGRES_USER=postgres
        - POSTGRES_PASSWORD=root
      volumes:
        - iniciando-django-pgdata:/var/lib/postgresql/data
    
    

volumes:
  iniciando-django-pgdata:
    external: true
  eco:
    external: true