# Generated by Django 3.0.6 on 2020-08-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('job_role', models.CharField(choices=[('dev', 'Desenvolvedor'), ('dba', 'Adminstrdor de Banco de Dados'), ('fte', 'Desenvolvedor Front-End')], max_length=3)),
                ('status', models.CharField(choices=[('A', 'Actived'), ('D', 'Deleted')], max_length=1)),
            ],
        ),
    ]
