# Generated by Django 3.0.6 on 2020-08-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naver',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
