# Generated by Django 3.0.6 on 2020-08-11 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Navers',
            new_name='Naver',
        ),
    ]
