# Generated by Django 3.0.6 on 2020-08-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200811_0209'),
        ('core', '0002_auto_20200811_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='naver',
            name='projects',
            field=models.ManyToManyField(to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='naver',
            name='job_role',
            field=models.CharField(choices=[('dev', 'Desenvolvedor'), ('dba', 'Adminstrdor de Banco de Dados'), ('fte', 'Desenvolvedor Front-End')], default='A', max_length=3),
        ),
        migrations.AlterField(
            model_name='naver',
            name='status',
            field=models.CharField(choices=[('A', 'Actived'), ('D', 'Deleted')], default='dev', max_length=1),
        ),
    ]
